version: '3'
services:
    logstash:
        build: .
        environment:
            - XPACK_MONITORING_ENABLED=false
        volumes:
            - ./pipeline:/usr/share/logstash/pipeline
        links:
            - mailhog

    filebeat:
        image: docker.elastic.co/beats/filebeat:6.5.2
        volumes:
            - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
            - ./logs:/usr/local/var/log:ro
        links:
            - logstash

    mailhog:
        image: mailhog/mailhog
        ports:
          - "8025:8025"
        expose:
          - "1025"

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:5.6.12
        environment:
          - http.host=0.0.0.0
          - transport.host=localhost
          - network.host=0.0.0.0
          # Disable X-Pack security: https://www.elastic.co/guide/en/elasticsearch/reference/5.6/security-settings.html#general-security-settings
          - xpack.security.enabled=false
          - xpack.watcher.enabled=false
          - xpack.monitoring.enabled=false
          - xpack.security.audit.enabled=false
          - xpack.ml.enabled=false
          - xpack.graph.enabled=false
          - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
          memlock:
            soft: -1
            hard: -1
        volumes:
            - es_data:/usr/share/elasticsearch/data
        ports:
            - 9200:9200

    mongodb:
        image: mongo:3
        volumes:
          - mongo_data:/data/db

    graylog:
        image: graylog/graylog:2.4.6-1
        volumes:
          - graylog_journal:/usr/share/graylog/data/journal
        links:
          - mongodb:mongo
          - elasticsearch
        depends_on:
          - mongodb
          - elasticsearch
        environment:
          # Set timezone in Docker container to timezone of all the other servers
          - TZ=Europe/Berlin
          - GRAYLOG_PASSWORD_SECRET=0eae038444a1991a7e62d5a5e1a07f1f
          # Password: admin
          - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
          - GRAYLOG_WEB_ENDPOINT_URI=http://127.0.0.1:9000/api
        ports:
          # Graylog web interface
          - 9000:9000
          # Syslog TCP
          # - 514:514
          # GELF TCP
          # - 12201:12201
          # GELF UDP
          - 12201:12201/udp

        # kibana:
        #     image: docker.elastic.co/kibana/kibana:5
        #     environment:
        #         - XPACK_MONITORING_ENABLED=false
        #         - ELASTICSEARCH_URL=elasticsearch

volumes:
  mongo_data:
    driver: local
  es_data:
    driver: local
  graylog_journal:
    driver: local
